[package]
name = "canali_a_priorità"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
rand = "0.9.1"
crossbeam-channel = "0.5.15"
